<?php

$layerNameToUse= $_GET['layerNameToUse'];
$lowerLeftXToUse= $_GET['lowerLeftXToUse'];
$lowerLeftYToUse= $_GET['lowerLeftYToUse'];
$upperRightXToUse= $_GET['upperRightXToUse'];
$upperRightYToUse= $_GET['upperRightYToUse'];
$wcsURL = $_GET['wcsURLToUse'];
$outputSrsToUse = $_GET['outputSrsToUse'];
$outputSrsToUse = (explode(":",$outputSrsToUse));
$outputSrsToUse = $outputSrsToUse[1];

$url = "$wcsURL?SERVICE=WCS&REQUEST=GetCoverage&VERSION=2.0.1&CoverageId=$layerNameToUse&compression=DEFLATE&subset=http://www.opengis.net/def/axis/OGC/0/X($lowerLeftXToUse,$upperRightXToUse)&subset=http://www.opengis.net/def/axis/OGC/0/Y($lowerLeftYToUse,$upperRightYToUse)&SUBSETTINGCRS=http://www.opengis.net/def/crs/EPSG/0/$outputSrsToUse";

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
//ini_set('memory_limit', '768M');
//ini_set('max_execution_time', 0);

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 0); 
$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);
#header('Content-type: image/geotiff');
echo $result;

?>